import { Google_Sans_Code } from "next/font/google";
import { Analytics } from '@vercel/analytics/next';
import "./globals.css";

const googleSansCode = Google_Sans_Code({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${googleSansCode.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
